### ISSUE TITLE
让证据非负的激活函数选择对结果的影响

### ISSUE THREAD

**Issue by roywang021** [Cogito2012/DEAR#3]
作者你好，看你的代码。让证据非负的激活函数在训练过程中默认是relu，在测试阶段再换成exp？不知道我的理解是否正确，以及这个函数的选择对最终的结果是否比较大呢？

**Comment by Cogito2012** [comment]
@roywang021 这个激活函数，我应该训练测试都是用exp。这篇[NeurIPS'18原文代码](https://github.com/dougbrion/pytorch-classification-uncertainty)默认用的是relu, 但我这里实验用relu不work。一般来说，需要保证训练、测试的激活函数一致。您可以根据自己的数据集和任务，找到合适的激活函数(relu, exp, softplus等)。

**Comment by roywang021** [comment]
您好，我想问下你的relu不work具体体现在哪里，或者你认为是什么原因呢？

**Comment by Cogito2012** [comment]
> 您好，我想问下你的relu不work具体体现在哪里，或者你认为是什么原因呢？

容易出现训练loss不收敛，最后测试效果很差。不过问过一些同行，他们做image任务用relu是可以work的。具体原因，可能是我没调好参数，也可能有理论方面的原因，有兴趣您也可以研究一下:)

**Comment by roywang021** [comment]
您好，我想问下EDL损失中的KL散度正则化项，前面的系数选择对最终结果影响大么？

**Comment by Cogito2012** [comment]
> 您好，我想问下EDL损失中的KL散度正则化项，前面的系数选择对最终结果影响大么？

影响挺大的，实验中发现KL散度项会降低performance，所以最终的config里面默认设置了`with_kldiv=False`。

**Comment by roywang021** [comment]
您好，我想问下你的relu不work具体体现在哪里，或者你认为是什么原因呢？因为我最近也在用EDL做东西，但是效果挺差的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cogito2012/DEAR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月29日(星期三) 中午1:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Cogito2012/DEAR] 让证据非负的激活函数选择对结果的影响 (Issue #3)





 
@roywang021 这个激活函数，我应该训练测试都是用exp。这篇NeurIPS'18原文代码默认用的是relu, 但我这里实验用relu不work。一般来说，需要保证训练、测试的激活函数一致。您可以根据自己的数据集和任务，找到合适的激活函数(relu, exp, softplus等)。

**Comment by roywang021** [comment]
谢谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wentao ***@***.***&gt;; 
发送时间: 2022年6月29日(星期三) 中午1:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Cogito2012/DEAR] 让证据非负的激活函数选择对结果的影响 (Issue #3)





 
@roywang021 这个激活函数，我应该训练测试都是用exp。这篇NeurIPS'18原文代码默认用的是relu, 但我这里实验用relu不work。一般来说，需要保证训练、测试的激活函数一致。您可以根据自己的数据集和任务，找到合适的激活函数(relu, exp, softplus等)。
